### PR TITLE
Print exception message now

### PR DESCRIPTION
**Pull request by AustinSeto**
App mentions URL when exception thrown

Addresses https://github.com/openliberty/guide-microprofile-rest-client/issues/113

### CODE REVIEW

**Review by TiagoF99 — APPROVED** [review]
Changes look good

**Review by gkwan-ibm — APPROVED** [review]
@AustinSeto I cannot get the error message you updated for at the browser or console. I doubt the problem is for "UnknownUriException".

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
@AustinSeto I cannot get the error message you updated for at the browser or console. I doubt the problem is for "UnknownUriException".

**Comment by AustinSeto** [comment]
@gkwan-ibm I recreated the scenario in #113 by modifying `src/main/webapp/META-INF/microprofile-config.properties` to change the port number in the URI. I was able to see a `ConnectException` with the bad URI in the console, so yes issue is not with handling of `UnknownURIException`. No changes made to what appears in browser. 

What is there right now shows `Unknown hostname or the system service may not be running on [hostname]` on any error or exception. Can look into a better way of showing exceptions/errors on browser.

**Review by griffinhadfield — APPROVED** [review]
Ran an end to end test, everything looks good to me.

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
@AustinSeto  should handle the UnknownUriException similarly

**Comment by gkwan-ibm** [comment]
also address issue: https://github.com/OpenLiberty/guides-common/issues/897

**Comment by gkwan-ibm** [comment]
close
- need to rework

**Pull request closed without merging**
